export type NavSectionKey =
  | 'workspace'
  | 'launch'
  | 'center'
  | 'bpm-assets'
  | 'admin'
  | 'system'
  | 'infra';

export interface ModuleConfig {
  key: string;
  section: NavSectionKey;
  label: string;
  description: string;
  permission?: string;
  path: string;
  listPath?: string;
  listMode?: 'list' | 'page';
  columns?: Array<{
    key: string;
    label: string;
  }>;
}

export interface SectionConfig {
  key: NavSectionKey;
  label: string;
  subtitle: string;
  to: string;
}

export const navSections: SectionConfig[] = [
  {
    key: 'workspace',
    label: '工作台',
    subtitle: '待办、超时、最近处理',
    to: '/workspace',
  },
  {
    key: 'launch',
    label: '发起审批',
    subtitle: '流程目录与常用发起',
    to: '/launch',
  },
  {
    key: 'center',
    label: '审批中心',
    subtitle: '待办、已办、我发起、抄送',
    to: '/center/todo',
  },
  {
    key: 'bpm-assets',
    label: '流程资产',
    subtitle: '模型、定义、表单、规则',
    to: '/assets/models',
  },
  {
    key: 'admin',
    label: '流程监管',
    subtitle: '实例、任务、报表',
    to: '/admin/instances',
  },
  {
    key: 'system',
    label: '系统管理',
    subtitle: '组织、权限、消息、租户',
    to: '/module/system-user',
  },
  {
    key: 'infra',
    label: '基础设施',
    subtitle: '文件、日志、配置',
    to: '/module/infra-file',
  },
];

export const moduleRegistry: ModuleConfig[] = [
  {
    key: 'bpm-category',
    section: 'bpm-assets',
    label: '流程分类',
    description: '维护审批分类和显示顺序',
    permission: 'bpm:category:query',
    path: '/assets/categories',
  },
  {
    key: 'bpm-form',
    section: 'bpm-assets',
    label: '流程表单',
    description: '动态表单结构与字段',
    permission: 'bpm:form:query',
    path: '/assets/forms',
  },
  {
    key: 'bpm-model',
    section: 'bpm-assets',
    label: '流程模型',
    description: '流程模型编排与部署源',
    permission: 'bpm:model:query',
    path: '/assets/models',
  },
  {
    key: 'bpm-definition',
    section: 'bpm-assets',
    label: '流程定义',
    description: '已部署流程定义和发起配置',
    permission: 'bpm:process-definition:query',
    path: '/assets/definitions',
  },
  {
    key: 'bpm-group',
    section: 'bpm-assets',
    label: '用户组',
    description: '审批候选组管理',
    permission: 'bpm:user-group:query',
    path: '/assets/groups',
  },
  {
    key: 'bpm-expression',
    section: 'bpm-assets',
    label: '流程表达式',
    description: '动态审批规则表达式库',
    permission: 'bpm:process-expression:query',
    path: '/assets/expressions',
  },
  {
    key: 'bpm-listener',
    section: 'bpm-assets',
    label: '流程监听器',
    description: '流程事件监听配置',
    permission: 'bpm:process-listener:query',
    path: '/assets/listeners',
  },
  {
    key: 'admin-instances',
    section: 'admin',
    label: '流程实例',
    description: '全局流程实例监管',
    permission: 'bpm:process-instance:manager-query',
    path: '/admin/instances',
  },
  {
    key: 'admin-tasks',
    section: 'admin',
    label: '流程任务',
    description: '全局任务队列监管',
    permission: 'bpm:task:manager-query',
    path: '/admin/tasks',
  },
  {
    key: 'admin-reports',
    section: 'admin',
    label: '流程报表',
    description: '流程实例筛选与报表',
    permission: 'bpm:process-instance:manager-query',
    path: '/admin/reports',
  },
  {
    key: 'system-user',
    section: 'system',
    label: '用户管理',
    description: '用户、状态、重置密码',
    permission: 'system:user:query',
    path: '/module/system-user',
    listPath: '/system/user/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'username', label: '用户名' },
      { key: 'nickname', label: '姓名' },
      { key: 'mobile', label: '手机号' },
      { key: 'status', label: '状态' },
    ],
  },
  {
    key: 'system-role',
    section: 'system',
    label: '角色管理',
    description: '角色、数据权限、菜单授权',
    permission: 'system:role:query',
    path: '/module/system-role',
    listPath: '/system/role/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '角色名' },
      { key: 'code', label: '角色编码' },
      { key: 'status', label: '状态' },
      { key: 'dataScope', label: '数据范围' },
    ],
  },
  {
    key: 'system-dept',
    section: 'system',
    label: '部门管理',
    description: '组织结构与负责人',
    permission: 'system:dept:query',
    path: '/module/system-dept',
    listPath: '/system/dept/list',
    listMode: 'list',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '部门名称' },
      { key: 'parentId', label: '上级部门' },
      { key: 'leaderUserId', label: '负责人' },
      { key: 'status', label: '状态' },
    ],
  },
  {
    key: 'system-menu',
    section: 'system',
    label: '菜单管理',
    description: '菜单、路由、权限点',
    permission: 'system:menu:query',
    path: '/module/system-menu',
    listPath: '/system/menu/list',
    listMode: 'list',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '名称' },
      { key: 'path', label: '路径' },
      { key: 'permission', label: '权限标识' },
      { key: 'status', label: '状态' },
    ],
  },
  {
    key: 'system-post',
    section: 'system',
    label: '岗位管理',
    description: '岗位定义与状态',
    permission: 'system:post:query',
    path: '/module/system-post',
    listPath: '/system/post/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '岗位名称' },
      { key: 'code', label: '岗位编码' },
      { key: 'sort', label: '排序' },
      { key: 'status', label: '状态' },
    ],
  },
  {
    key: 'system-dict-type',
    section: 'system',
    label: '字典类型',
    description: '字典类型配置',
    permission: 'system:dict:query',
    path: '/module/system-dict-type',
    listPath: '/system/dict-type/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '名称' },
      { key: 'type', label: '字典类型' },
      { key: 'status', label: '状态' },
    ],
  },
  {
    key: 'system-dict-data',
    section: 'system',
    label: '字典数据',
    description: '字典值和颜色语义',
    permission: 'system:dict:query',
    path: '/module/system-dict-data',
    listPath: '/system/dict-data/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'dictType', label: '字典类型' },
      { key: 'label', label: '标签' },
      { key: 'value', label: '值' },
      { key: 'status', label: '状态' },
    ],
  },
  {
    key: 'system-notice',
    section: 'system',
    label: '通知公告',
    description: '公告发布与状态',
    permission: 'system:notice:query',
    path: '/module/system-notice',
    listPath: '/system/notice/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'title', label: '标题' },
      { key: 'status', label: '状态' },
      { key: 'createTime', label: '创建时间' },
    ],
  },
  {
    key: 'system-social-client',
    section: 'system',
    label: '社交客户端',
    description: '钉钉、企业微信、Gitee 等社交登录配置',
    permission: 'system:social-client:query',
    path: '/module/system-social-client',
    listPath: '/system/social-client/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '名称' },
      { key: 'socialType', label: '平台' },
      { key: 'clientId', label: 'Client ID' },
      { key: 'status', label: '状态' },
    ],
  },
  {
    key: 'system-social-user',
    section: 'system',
    label: '社交用户',
    description: '第三方账号绑定关系与社交用户信息',
    permission: 'system:social-user:query',
    path: '/module/system-social-user',
    listPath: '/system/social-user/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'type', label: '平台类型' },
      { key: 'openid', label: 'OpenID' },
      { key: 'nickname', label: '昵称' },
      { key: 'createTime', label: '创建时间' },
    ],
  },
  {
    key: 'system-notify-message',
    section: 'system',
    label: '站内信消息',
    description: '消息投递、已读状态与用户消息记录',
    permission: 'system:notify-message:query',
    path: '/module/system-notify-message',
    listPath: '/system/notify-message/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'templateCode', label: '模板编码' },
      { key: 'templateNickname', label: '发送人' },
      { key: 'readStatus', label: '已读' },
      { key: 'createTime', label: '发送时间' },
    ],
  },
  {
    key: 'system-notify-template',
    section: 'system',
    label: '站内信模板',
    description: '站内信模板定义与发送测试',
    permission: 'system:notify-template:query',
    path: '/module/system-notify-template',
    listPath: '/system/notify-template/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '模板名称' },
      { key: 'code', label: '模板编码' },
      { key: 'status', label: '状态' },
      { key: 'createTime', label: '创建时间' },
    ],
  },
  {
    key: 'system-mail-account',
    section: 'system',
    label: '邮箱账号',
    description: '发信账号、SMTP 配置与默认账号',
    permission: 'system:mail-account:query',
    path: '/module/system-mail-account',
    listPath: '/system/mail-account/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'mail', label: '邮箱' },
      { key: 'username', label: '用户名' },
      { key: 'host', label: 'SMTP 主机' },
      { key: 'status', label: '状态' },
    ],
  },
  {
    key: 'system-mail-template',
    section: 'system',
    label: '邮件模板',
    description: '邮件通知模板与测试发送',
    permission: 'system:mail-template:query',
    path: '/module/system-mail-template',
    listPath: '/system/mail-template/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '模板名称' },
      { key: 'code', label: '模板编码' },
      { key: 'title', label: '邮件标题' },
      { key: 'status', label: '状态' },
    ],
  },
  {
    key: 'system-mail-log',
    section: 'system',
    label: '邮件日志',
    description: '发信结果、接收人和异常原因',
    permission: 'system:mail-log:query',
    path: '/module/system-mail-log',
    listPath: '/system/mail-log/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'toMail', label: '收件人' },
      { key: 'subject', label: '主题' },
      { key: 'sendStatus', label: '发送状态' },
      { key: 'createTime', label: '发送时间' },
    ],
  },
  {
    key: 'system-sms-channel',
    section: 'system',
    label: '短信渠道',
    description: '短信供应商渠道与签名配置',
    permission: 'system:sms-channel:query',
    path: '/module/system-sms-channel',
    listPath: '/system/sms-channel/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'signature', label: '签名' },
      { key: 'code', label: '渠道编码' },
      { key: 'status', label: '状态' },
      { key: 'createTime', label: '创建时间' },
    ],
  },
  {
    key: 'system-sms-template',
    section: 'system',
    label: '短信模板',
    description: '短信模板维护与测试发送',
    permission: 'system:sms-template:query',
    path: '/module/system-sms-template',
    listPath: '/system/sms-template/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '模板名称' },
      { key: 'code', label: '模板编码' },
      { key: 'status', label: '状态' },
      { key: 'createTime', label: '创建时间' },
    ],
  },
  {
    key: 'system-sms-log',
    section: 'system',
    label: '短信日志',
    description: '短信发送记录、手机号和回执状态',
    permission: 'system:sms-log:query',
    path: '/module/system-sms-log',
    listPath: '/system/sms-log/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'mobile', label: '手机号' },
      { key: 'templateCode', label: '模板编码' },
      { key: 'sendStatus', label: '发送状态' },
      { key: 'createTime', label: '发送时间' },
    ],
  },
  {
    key: 'system-oauth2-client',
    section: 'system',
    label: 'OAuth2 客户端',
    description: '客户端凭据、授权范围与回调配置',
    permission: 'system:oauth2-client:query',
    path: '/module/system-oauth2-client',
    listPath: '/system/oauth2-client/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'clientId', label: 'Client ID' },
      { key: 'name', label: '名称' },
      { key: 'status', label: '状态' },
      { key: 'createTime', label: '创建时间' },
    ],
  },
  {
    key: 'system-oauth2-token',
    section: 'system',
    label: 'OAuth2 令牌',
    description: '访问令牌、用户和过期时间',
    permission: 'system:oauth2-token:query',
    path: '/module/system-oauth2-token',
    listPath: '/system/oauth2-token/page',
    listMode: 'page',
    columns: [
      { key: 'userId', label: '用户 ID' },
      { key: 'userType', label: '用户类型' },
      { key: 'clientId', label: 'Client ID' },
      { key: 'expiresTime', label: '到期时间' },
      { key: 'createTime', label: '签发时间' },
    ],
  },
  {
    key: 'system-area',
    section: 'system',
    label: '地区管理',
    description: '地区树、编码和 IP 所属地能力',
    permission: 'system:area:query',
    path: '/module/system-area',
    listPath: '/system/area/tree',
    listMode: 'list',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '地区名称' },
      { key: 'code', label: '地区编码' },
      { key: 'parentId', label: '父级 ID' },
      { key: 'sort', label: '排序' },
    ],
  },
  {
    key: 'system-login-log',
    section: 'system',
    label: '登录日志',
    description: '登录行为记录',
    permission: 'system:login-log:query',
    path: '/module/system-login-log',
    listPath: '/system/login-log/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'username', label: '用户名' },
      { key: 'userIp', label: 'IP' },
      { key: 'result', label: '结果' },
      { key: 'createTime', label: '时间' },
    ],
  },
  {
    key: 'system-operate-log',
    section: 'system',
    label: '操作日志',
    description: '系统操作审计',
    permission: 'system:operate-log:query',
    path: '/module/system-operate-log',
    listPath: '/system/operate-log/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'userName', label: '操作人' },
      { key: 'type', label: '业务类型' },
      { key: 'requestUrl', label: '请求地址' },
      { key: 'createTime', label: '时间' },
    ],
  },
  {
    key: 'system-tenant',
    section: 'system',
    label: '租户管理',
    description: '租户与到期时间',
    permission: 'system:tenant:query',
    path: '/module/system-tenant',
    listPath: '/system/tenant/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '租户名' },
      { key: 'contactName', label: '联系人' },
      { key: 'status', label: '状态' },
      { key: 'expireTime', label: '到期时间' },
    ],
  },
  {
    key: 'system-tenant-package',
    section: 'system',
    label: '租户套餐',
    description: '套餐和菜单授权',
    permission: 'system:tenant-package:query',
    path: '/module/system-tenant-package',
    listPath: '/system/tenant-package/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '套餐名称' },
      { key: 'status', label: '状态' },
      { key: 'remark', label: '备注' },
    ],
  },
  {
    key: 'infra-file',
    section: 'infra',
    label: '文件存储',
    description: '上传文件与 URL',
    permission: 'infra:file:query',
    path: '/module/infra-file',
    listPath: '/infra/file/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '文件名' },
      { key: 'path', label: '路径' },
      { key: 'size', label: '大小' },
      { key: 'createTime', label: '创建时间' },
    ],
  },
  {
    key: 'infra-file-config',
    section: 'infra',
    label: '文件配置',
    description: '存储配置与启用状态',
    permission: 'infra:file-config:query',
    path: '/module/infra-file-config',
    listPath: '/infra/file-config/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '名称' },
      { key: 'storage', label: '存储器' },
      { key: 'master', label: '主配置' },
      { key: 'status', label: '状态' },
    ],
  },
  {
    key: 'infra-api-access-log',
    section: 'infra',
    label: 'API 访问日志',
    description: '访问链路与耗时',
    permission: 'infra:api-access-log:query',
    path: '/module/infra-api-access-log',
    listPath: '/infra/api-access-log/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'requestMethod', label: '方法' },
      { key: 'requestUrl', label: '地址' },
      { key: 'resultCode', label: '结果码' },
      { key: 'createTime', label: '时间' },
    ],
  },
  {
    key: 'infra-api-error-log',
    section: 'infra',
    label: 'API 错误日志',
    description: '异常日志与处理状态',
    permission: 'infra:api-error-log:query',
    path: '/module/infra-api-error-log',
    listPath: '/infra/api-error-log/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'exceptionName', label: '异常' },
      { key: 'requestUrl', label: '请求地址' },
      { key: 'processStatus', label: '处理状态' },
      { key: 'createTime', label: '时间' },
    ],
  },
  {
    key: 'infra-job',
    section: 'infra',
    label: '定时任务',
    description: '任务调度、Cron、重试和执行状态',
    permission: 'infra:job:query',
    path: '/module/infra-job',
    listPath: '/infra/job/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '任务名称' },
      { key: 'handlerName', label: '处理器' },
      { key: 'status', label: '状态' },
      { key: 'cronExpression', label: 'Cron' },
    ],
  },
  {
    key: 'infra-job-log',
    section: 'infra',
    label: '任务日志',
    description: '调度执行记录、耗时和结果',
    permission: 'infra:job:query',
    path: '/module/infra-job-log',
    listPath: '/infra/job-log/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'jobId', label: '任务 ID' },
      { key: 'handlerName', label: '处理器' },
      { key: 'status', label: '状态' },
      { key: 'beginTime', label: '开始时间' },
    ],
  },
  {
    key: 'infra-config',
    section: 'infra',
    label: '参数配置',
    description: '系统参数、可见性和配置分类',
    permission: 'infra:config:query',
    path: '/module/infra-config',
    listPath: '/infra/config/page',
    listMode: 'page',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'category', label: '分类' },
      { key: 'name', label: '参数名称' },
      { key: 'key', label: '参数键名' },
      { key: 'visible', label: '可见' },
    ],
  },
  {
    key: 'infra-data-source-config',
    section: 'infra',
    label: '数据源配置',
    description: '代码生成和多数据源连接配置',
    permission: 'infra:data-source-config:query',
    path: '/module/infra-data-source-config',
    listPath: '/infra/data-source-config/list',
    listMode: 'list',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: '名称' },
      { key: 'url', label: '连接地址' },
      { key: 'username', label: '用户名' },
      { key: 'createTime', label: '创建时间' },
    ],
  },
  {
    key: 'infra-redis',
    section: 'infra',
    label: 'Redis 监控',
    description: '缓存概览、内存使用与命令统计',
    permission: 'infra:redis:query',
    path: '/module/infra-redis',
  },
  {
    key: 'infra-codegen',
    section: 'infra',
    label: '代码生成',
    description: '生成表配置、模块名和业务名维护',
    permission: 'infra:codegen:query',
    path: '/module/infra-codegen',
    listPath: '/infra/codegen/table/page',
    listMode: 'page',
    columns: [
      { key: 'tableName', label: '表名' },
      { key: 'tableComment', label: '表说明' },
      { key: 'moduleName', label: '模块名' },
      { key: 'businessName', label: '业务名' },
      { key: 'className', label: '类名' },
    ],
  },
];

export function getSectionModules(section: NavSectionKey) {
  return moduleRegistry.filter((item) => item.section === section);
}
