CREATE TABLE IF NOT EXISTS `bpm_approval_template` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '模板编号',
  `code` varchar(63) NOT NULL COMMENT '模板编码',
  `name` varchar(127) NOT NULL COMMENT '模板名称',
  `description` varchar(255) DEFAULT '' COMMENT '模板描述',
  `icon` varchar(255) DEFAULT '' COMMENT '模板图标',
  `category` varchar(63) NOT NULL COMMENT '流程分类编码',
  `visible` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否上架',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序值',
  `process_definition_id` varchar(255) NOT NULL COMMENT '绑定的流程定义编号',
  `process_definition_key` varchar(255) NOT NULL COMMENT '绑定的流程定义标识',
  `model_id` varchar(255) DEFAULT '' COMMENT '绑定的流程模型编号',
  `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bpm_approval_template_code` (`code`),
  KEY `idx_bpm_approval_template_process_definition_id` (`process_definition_id`),
  KEY `idx_bpm_approval_template_process_definition_key` (`process_definition_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='BPM 审批模板';
